In [1]:
import pandas as pd

In [2]:
import mysql.connector

In [3]:
conn = mysql.connector.connect(
    host='database-streamlit.czq8ik4asj60.ap-southeast-1.rds.amazonaws.com',       # e.g., 'localhost' or your RDS endpoint
    user='admin',
    password='f*_anVhnyYFRK8veG',
    database='streamlit_ecliptor'
)

In [4]:
conn = mysql.connector.connect(
    host='database-streamlit.czq8ik4asj60.ap-southeast-1.rds.amazonaws.com',
    user='admin',
    password='f*_anVhnyYFRK8veG',
    database='streamlit_ecliptor'
)

cursor = conn.cursor()

# Execute the query to show all tables
cursor.execute("SHOW TABLES;")
tables = cursor.fetchall()

# Display the tables
if tables:
    print("Tables in the database:")
    for table in tables:
        print(table[0])  # Print each table name
else:
    print("No tables found in the database.")

# Close the connection
cursor.close()
conn.close()

Tables in the database:
agent_actions
documents
peer_review_actions
peer_review_documents

In [8]:
conn = mysql.connector.connect(
    host='database-streamlit.czq8ik4asj60.ap-southeast-1.rds.amazonaws.com',
    user='admin',
    password='f*_anVhnyYFRK8veG',
    database='streamlit_ecliptor'
)

cursor = conn.cursor()

# Execute the query to select all records from agent_actions
cursor.execute("SELECT * FROM peer_review_actions;")
agent_actions = cursor.fetchall()

# Get column names
column_names = [i[0] for i in cursor.description]

# Create a DataFrame
df_agent_actions = pd.DataFrame(agent_actions, columns=column_names)

# Display the DataFrame
df_agent_actions

# Close the connection
cursor.close()
conn.close()

In [10]:
df_agent_actions.created_at.max()

Timestamp('2024-12-03 07:28:03')

In [15]:
conn = mysql.connector.connect(
    host='database-streamlit.czq8ik4asj60.ap-southeast-1.rds.amazonaws.com',
    user='admin',
    password='f*_anVhnyYFRK8veG',
    database='streamlit_ecliptor'
)

cursor = conn.cursor()

# Define the query to randomly select 20 IDs per name
query = """
SELECT id, name FROM (
    SELECT id, name,
           ROW_NUMBER() OVER (PARTITION BY name ORDER BY RAND()) as rn
    FROM agent_actions
    WHERE name IN ('Aki', 'Andee', 'Ari', 'CB - Carlo', 'Carl', 'Mojie')
) as subquery
WHERE rn <= 20;
"""

# Execute the query
cursor.execute(query)
random_ids_per_name = cursor.fetchall()

# Get column names
column_names = [i[0] for i in cursor.description]

# Create a DataFrame
df_random_ids_per_name = pd.DataFrame(random_ids_per_name, columns=column_names)



# Close the connection
cursor.close()
conn.close()

In [24]:
list(df_random_ids_per_name.id)

['615e69e0-a0b2-4435-9a50-a1b82036a87c',
 '290007a4-6b7a-4363-9881-8777fd42d8dc',
 '2ea63fae-b18c-46ff-a848-0c1579db3915',
 '868d2b16-f66e-4ee2-a641-cac29c0b60c5',
 '68c02ab4-2521-4ffc-9aaa-3e10a4295f65',
 '8bec9bfd-0bcb-40e7-958f-f979e7793b20',
 '569cb28c-fe20-432f-8595-e9c633ace3c6',
 'a512cad0-34d1-4a93-b3da-01a15e639d44',
 '5fe76d9e-53ce-409c-9146-de1a2ae49b52',
 '32cd505b-0b37-4132-95b2-c25e4df4f62b',
 '3c8e59af-d72f-4e8d-9b5e-63337b3b4d63',
 'd7a4ee5d-2cbe-42f4-ab4e-5dc71674c847',
 'f8e545d4-7bec-4fe3-abaf-356156a31467',
 '2793f72e-f94d-493a-b96c-932f442b7946',
 'ff4d879f-6509-4ace-8f3e-7ea58e1544c2',
 'c3a21926-a920-415e-8517-96acfe2a3c79',
 'fd45de18-9243-4b7f-a883-ac2fb2069fa0',
 'fa206ce8-d1b5-4019-b97e-ff413fda4a2f',
 '2ff5806d-5a71-477f-88c4-d9b183560767',
 'fd50f41f-ca2a-41d2-862c-b9088cc86507',
 '443d3dd0-2afd-40b9-914a-f9ec2391cd57',
 'd2520e44-7f85-4788-85f3-79d9632926bd',
 '57976f1a-02cc-4e51-929b-aaf6e7e97f72',
 '6c9a4d86-ecf4-4728-aad1-c2f28a6a8745',
 '31d456de-7457-48b3-ac8a-e4a91570003a',
 '5da7602b-0ecb-4363-b100-ba58e33d29c9',
 '6c86d483-45a0-428c-b5a3-5b93c1d424d1',
 'e7eaed86-ce2e-4c55-96ff-5c248a9ef7c8',
 '52f3e265-8102-4171-b433-d1d2ef167ba5',
 '6b12e07e-05e8-4a70-975d-68e20adf1ae6',
 'd84b5d9c-34b2-40a1-8e84-58c9612a597e',
 '6cf551c4-a9f2-4a7a-bef4-7e2034f7e8fb',
 '615f5d4d-7439-46ec-999f-fdd9ec1a4cec',
 'b0cb119a-c32b-4f86-84ac-8b2ed83ba6e3',
 '24a834e9-e575-4867-ab4c-89693d1c04f2',
 '1d7ce363-b002-48b3-83bc-aa252860149c',
 '924fb309-6b74-4741-b365-00f9df885b31',
 'd0aa3fec-cc0a-4966-b0ad-43b7f47fc310',
 '485fa566-6600-4243-911b-3a61bac960aa',
 '7ed0d387-9d51-4782-a489-181c91995dbc',
 '0d60bcf0-f088-4250-8622-93d439f6a8f2',
 '0b14fe76-f006-4479-93aa-6d7b5301c2c5',
 'd250f04e-045f-47a2-8cdb-2d72624fb9f6',
 '5f24900b-1d0f-4201-bd7a-14f27e41d9ca',
 '75eb36ed-d058-4bdc-b9d6-b68468edebe4',
 '76e44473-1c90-4e0a-85cb-4aa49b63f4e5',
 '2c980e7e-cd1f-48d0-9d37-25caed0e4acb',
 '794a1f04-e0fd-4362-b066-6074b46d55df',
 '5d129fa9-03c9-47c0-8738-a431c8c7c6e8',
 'd68e5c62-6aca-4274-a141-d50baf737818',
 '4d40ae62-f97b-4ea7-bb73-d279409774b1',
 '85ec7898-fdb2-416a-8e1c-02d872e77ea8',
 '78cb0334-12e3-4dd9-b8a1-a0d3fb2f5695',
 '3686d5ed-57a0-4d11-8244-738ff33815b5',
 '1abba4be-024b-4677-b70c-437c7e39f847',
 '9f2e6963-19c1-41c5-9235-8e126c7ecb0d',
 'd09e6c5a-65d8-45c1-b304-6f39495fcfbf',
 'caf189c9-5c4e-4339-b207-18fc02973bba',
 '496ce895-ab22-4c30-ab08-4fab9768f1e6',
 '25e0bc2f-7a38-43f0-afe7-cc5e33792dac',
 '71a0a7dd-8318-44a4-a535-adcbdc0ed9dc',
 'c0cb24b7-e949-47c3-ae02-bbf274d25179',
 '98474d57-8cd0-4aaf-811e-de97475817e5',
 '0414194a-873e-4cc9-a648-8e214c073a28',
 '12820151-dbcf-4e6b-8695-9c3f8ddaddd8',
 '3cfea882-c550-4263-8739-a7e531bd67e0',
 '4549c999-9f58-4b1c-a190-26808afed705',
 'afddb8c3-d4d3-4ec6-a0f4-5c45335ef259',
 'a11de471-07ba-45cb-9d90-b6f3ec683d30',
 'b0efd271-551a-4a8b-af95-fa26aa0aea34',
 '48b4f0da-e6db-49fa-a2ee-08e40623c8dc',
 '75cabc34-6936-43fb-9f1c-2e009e511f4e',
 'bf50945f-77e0-4f0b-a6e5-08a6da4032f6',
 'deb1cbce-66ce-4230-99f9-ba65ecb51af6',
 '325e4c2e-4adb-4b2c-898b-516c7f549487',
 'ce5565bf-28aa-4e8e-85af-92abab2f75ac',
 '0fc9198c-d721-4517-bd04-db0cf5162842',
 '76aa2f29-0d52-4b04-a426-55a90aae8e03',
 'a0c29bf4-6ea8-47f3-adc3-693cd23451e4',
 '2aedbdd1-a547-4892-8173-bf7d388c46eb',
 '4ac7c1cc-1346-40bc-ac37-0542c69edefa',
 '8f1c4729-22c8-47ca-a44c-e64af927cd96',
 '752d9321-2063-49b4-98ce-33e088743ce9',
 '09cfdce9-f4b4-45f1-9a56-163b12f36071',
 'f822d519-b2e9-47ea-bbbe-cdbaff307273',
 'f7861b77-8888-4aea-bd8c-5b1a8eb09061',
 '75bc71af-3e90-42b1-bb2d-338bd38c0c5f',
 'bb8094c4-eea8-46aa-838f-0509284251fa',
 '15825b94-45e2-4300-a468-60333f3237d3',
 '829c81e7-1a83-4240-b580-ad4c2d59a0a1',
 '1fcb2b90-671a-479c-8451-e277954b72f8',
 '065a35f8-ed7a-4421-8139-e25880ba0cd7',
 '3fdee01d-d6c8-41d3-a8fa-438d937deb9d',
 '0f8b157a-db09-4bcc-9440-e7d7fb5aaf0e',
 'ff234845-aa04-4cde-ae40-d36924c1e45c',
 '5c0923be-6c8e-40d9-8682-4319424182f9',
 '2650333b-066f-450d-a30e-a1c2899055cd',
 'd899d9f6-77b4-4b34-952c-538c42d97dd3',
 '80b3c05d-98c2-43bb-bf3c-5c57698a5fec',
 '1befc15d-2e2b-4b75-8422-21dc4e5ff98c',
 'c7c357fa-5ca6-455a-83e7-5881640114a0',
 '435a244f-75ea-4c46-a589-ac33237bc5fc',
 'ab2ee2bc-b761-4859-be0e-f9962ef21d94',
 '5d2d69f3-c711-41e4-b3e1-6c48ece2fb17',
 '3aa32500-2e49-499b-a59b-9d478d17b0de',
 'aebba63b-c9b3-4567-8d42-374d11ce3bb0',
 '1e89c958-6344-45e7-8018-7a2685142d49',
 '7773706c-b32f-4aa0-8114-c79788bbf406',
 '31add6e1-57b4-46c5-aaf5-f1700e94d786',
 '6c26a040-6280-4097-a17f-2f0fecdaa703',
 'c3bb072d-47bd-4d92-ac3e-d4133ca54fce',
 '5bc4b9f0-9eab-4b4b-b09b-ff61f6b6254d',
 '89b55039-ff02-4d2a-8208-0b386b1c6556',
 'a45bd4d6-8144-4c03-82a0-d320551967e4',
 'b52894b7-44eb-4e0c-991a-a8a933f2f58e',
 '9fc63ec9-8b9f-4378-a41c-15ce77e74791',
 'f7d5baec-a8e9-4238-9b60-f689d1f97da3',
 'fc11360f-98b1-4130-b782-a3a3fc6af408',
 '567d5a11-94f5-496a-a675-a031a8d334f2',
 '2c8ed4f2-953b-4bfc-8d04-3b1f84efb295']

In [54]:
conn = mysql.connector.connect(
    host='database-streamlit.czq8ik4asj60.ap-southeast-1.rds.amazonaws.com',
    user='admin',
    password='f*_anVhnyYFRK8veG',
    database='streamlit_ecliptor'
)

cursor = conn.cursor()

# Define the query to select all records from peer_review_documents
query = "SELECT * FROM peer_review_documents;"

# Execute the query
cursor.execute(query)
peer_review_documents = cursor.fetchall()

# Get column names
column_names = [i[0] for i in cursor.description]

# Create a DataFrame
df_peer_review_documents = pd.DataFrame(peer_review_documents, columns=column_names)

# Close the connection
cursor.close()
conn.close()

In [55]:
df_peer_review_documents

,id,agent_action_id,document_id,review_index,created_at
0,0242938b-d229-4bcf-9201-76ea4f415206,7ed0d387-9d51-4782-a489-181c91995dbc,3d8ecade-81b4-45a2-a24e-9c82e3df88e8,237,2024-12-17 15:04:35
1,029242a0-2fe5-4d12-820f-9c699368eea0,569cb28c-fe20-432f-8595-e9c633ace3c6,a0db60ab-a266-11ef-9f70-027638034b15,190,2024-12-17 15:04:35
2,02f777ef-60b2-4b19-9c6b-a551bac54147,48b4f0da-e6db-49fa-a2ee-08e40623c8dc,9efe6fe8-a266-11ef-9f70-027638034b15,239,2024-12-17 15:04:35
3,058c5f93-14c9-4aee-b58d-61c47f5a4764,4549c999-9f58-4b1c-a190-26808afed705,f15d4179-cb96-4f38-b063-45da2c4032f1,180,2024-12-17 15:04:35
4,09082763-d5b3-4e6b-9fa6-898140cb4c28,d09e6c5a-65d8-45c1-b304-6f39495fcfbf,a9011921-afb1-11ef-9f70-027638034b15,219,2024-12-17 15:04:35
...,...,...,...,...,...
235,fc956e00-132c-4601-bd8b-1904cc1b36e5,470b2214-76b0-4194-aa79-05197c62ac18,559c2f0e-7a8e-48cd-af49-3379254a32a2,48,2024-12-01 07:49:30
236,fe2eefec-8df7-48fd-bdcb-77877876fbaa,97256f89-9542-40db-9b1d-6744dd49a62f,181b57db-e641-4fcb-a21d-a911810dade4,32,2024-12-01 07:49:29
237,fe9b1483-d83b-4954-90c2-5d623f1a434c,aebba63b-c9b3-4567-8d42-374d11ce3bb0,b5dec9c3-58c4-488d-a008-dc9e9ef03bf2,130,2024-12-17 15:04:35
238,fefcaf73-e577-4779-9750-5a7c0b001913,09cfdce9-f4b4-45f1-9a56-163b12f36071,41d89bb2-53d9-40b5-b4e8-119945b109af,227,2024-12-17 15:04:35
239,ff57cf0a-fde7-48fb-a098-31dbd8493ed4,325e4c2e-4adb-4b2c-898b-516c7f549487,be4865e6-5fa5-4b5a-816d-887784d8ff37,141,2024-12-17 15:04:35

In [30]:
conn = mysql.connector.connect(
    host='database-streamlit.czq8ik4asj60.ap-southeast-1.rds.amazonaws.com',
    user='admin',
    password='f*_anVhnyYFRK8veG',
    database='streamlit_ecliptor'
)

cursor = conn.cursor()

# Assuming df_random_agent_action_ids_per_name is already defined
agent_action_ids = list(df_random_ids_per_name.id)

# Convert the list to a string format suitable for SQL IN clause
ids_tuple = tuple(agent_action_ids)

# Define the query to join tables on document_id and filter by agent_action_id
query = f"""
SELECT a.id as agent_action_id, d.id as document_id
FROM agent_actions a
JOIN documents d ON a.document_id = d.id
WHERE a.id IN {ids_tuple};
"""

# Execute the query
cursor.execute(query)
joined_data = cursor.fetchall()

# Get column names
column_names = [i[0] for i in cursor.description]

# Create a DataFrame
df_joined_data = pd.DataFrame(joined_data, columns=column_names)

# Close the connection
cursor.close()
conn.close()

In [41]:
df_joined_data = df_joined_data.sample(frac=1).reset_index(drop=True)

In [47]:
last_index =  df_peer_review_documents.review_index.max()
df_joined_data['review_index'] = df_joined_data.index + last_index + 1

In [53]:
import uuid
from datetime import datetime

# Add 'id' and 'created_at' columns to the DataFrame
df_joined_data['id'] = [str(uuid.uuid4()) for _ in range(len(df_joined_data))]
df_joined_data['created_at'] = datetime.now()

# Re-establish the database connection
conn = mysql.connector.connect(
    host='database-streamlit.czq8ik4asj60.ap-southeast-1.rds.amazonaws.com',       # e.g., 'localhost' or your RDS endpoint
    user='admin',
    password='f*_anVhnyYFRK8veG',
    database='streamlit_ecliptor'
)

cursor = conn.cursor()

# Insert each row into the peer_review_documents table
insert_query = """
INSERT INTO peer_review_documents (id, agent_action_id, document_id, review_index, created_at)
VALUES (%s, %s, %s, %s, %s)
"""

for _, row in df_joined_data.iterrows():
    cursor.execute(insert_query, (
        row['id'],
        row['agent_action_id'],
        row['document_id'],
        row['review_index'],
        row['created_at']
    ))

# Commit the transaction
conn.commit()

# Close the connection
cursor.close()
conn.close()

In [49]:
df_joined_data

,agent_action_id,document_id,review_index
0,a512cad0-34d1-4a93-b3da-01a15e639d44,8fead86f-9566-45b7-a112-047b1a3d20e3,121
1,31add6e1-57b4-46c5-aaf5-f1700e94d786,93777bca-0b4d-478e-a72b-061db02b827b,122
2,75eb36ed-d058-4bdc-b9d6-b68468edebe4,bb7155bb-afb1-11ef-9f70-027638034b15,123
3,71a0a7dd-8318-44a4-a535-adcbdc0ed9dc,c54de8eb-1ffe-429c-938b-b1720f67bd22,124
4,868d2b16-f66e-4ee2-a641-cac29c0b60c5,6d0cd775-9752-4bda-b80b-fb8fbfdb86f7,125
...,...,...,...
115,5bc4b9f0-9eab-4b4b-b09b-ff61f6b6254d,b6307d8c-afb1-11ef-9f70-027638034b15,236
116,7ed0d387-9d51-4782-a489-181c91995dbc,3d8ecade-81b4-45a2-a24e-9c82e3df88e8,237
117,9fc63ec9-8b9f-4378-a41c-15ce77e74791,bd12fa6f-afb1-11ef-9f70-027638034b15,238
118,48b4f0da-e6db-49fa-a2ee-08e40623c8dc,9efe6fe8-a266-11ef-9f70-027638034b15,239
119,5fe76d9e-53ce-409c-9146-de1a2ae49b52,9f8e069b-a266-11ef-9f70-027638034b15,240

In [10]:
import boto3

bucket_name = 'streamlit-images'
region = 'ap-southeast-1'  # e.g., 'us-east-1'

s3_client = boto3.client('s3', region_name=region)

paginator = s3_client.get_paginator('list_objects_v2')
pages = paginator.paginate(Bucket=bucket_name)

with open('image_urls.csv', 'w') as file:
    for page in pages:
        for obj in page.get('Contents', []):
            key = obj['Key']
            url = f'https://{bucket_name}.s3.{region}.amazonaws.com/{key}'
            file.write(f"{key},{url}\n")

In [ ]:
import os
import uuid
import pandas as pd

def create_document_entries(images_dir: str, markdown_dir: str, output_csv: str):
    files_with_no_md = 0
    """
    Create document entries from image and markdown files.

    Args:
        images_dir: Path to directory containing image files
        markdown_dir: Path to directory containing markdown files
        output_csv: Path where to save the CSV file
    """
    # Get a list of all image files
    image_files = [f for f in os.listdir(images_dir) if f.endswith(('.png', '.jpg', '.jpeg'))]

    # Initialize a list to hold document data
    documents = []

    for index, image_file in enumerate(image_files, start=1):
        index = index + 198
        # Generate a UUID
        document_uuid = str(uuid.uuid4())

        # Extract the base filename without extension
        base_filename = os.path.splitext(image_file)[0]

        # Construct the full paths
        image_path = os.path.join(images_dir, image_file)
        markdown_filename = f"{base_filename}.md"
        markdown_path = os.path.join(markdown_dir, markdown_filename)

        # Read the markdown content if it exists
        if os.path.exists(markdown_path):
            with open(markdown_path, 'r', encoding='utf-8') as md_file:
                markdown_content = md_file.read()
        else:
            markdown_content = ''
            print(f"Warning: Markdown file not found for {image_file}")
            files_with_no_md += 1


        # Create document entry
        documents.append({
            'id': document_uuid,
            'doc_index': index,
            'image_path': image_path,
            'markdown': markdown_content
        })

    print(files_with_no_md)

    # Create a DataFrame and save to CSV
    df = pd.DataFrame(documents)
    df[['doc_index', 'image_path', 'markdown']].to_csv(output_csv, index=False)

    print(f"Created {len(documents)} document entries")
    print(f"Saved to {output_csv}")

In [162]:
IMAGES_DIR = '/Users/paulobautista/Documents/ecliptor/huggingface_ds_1/huggingface_ds_1_raw'
MARKDOWN_DIR = '/Users/paulobautista/Documents/ecliptor/huggingface_ds_1/md_init'
OUTPUT_CSV = '/Users/paulobautista/Documents/ecliptor/huggingface_ds_1/document_db.csv'

In [180]:
df = pd.read_csv('/Users/paulobautista/Documents/ecliptor/huggingface_ds_1/document_db.csv')

In [181]:
def clean_image_path(path):
  path = path.split('/')[-1]
  return 'image/'+path

In [182]:
df.image_path = df.image_path.apply(clean_image_path)

In [183]:
df = df.dropna(subset=['markdown'])

In [187]:
df = df.reset_index(drop=True)

In [188]:
df.doc_index = df.index + 199

In [189]:
df.doc_index = df.index + 199

In [ ]:
from datetime import datetime

In [ ]:
conn = mysql.connector.connect(
    host='database-streamlit.czq8ik4asj60.ap-southeast-1.rds.amazonaws.com',
    user='admin',
    password='f*_anVhnyYFRK8veG',
    database='streamlit_ecliptor'
)
cursor = conn.cursor()


for index,row in df.iterrows():
  try:
    query = """
    INSERT INTO documents
    (id, doc_index, markdown, image_path, created_at)
    VALUES (%s, %s, %s, %s, %s)
    """

    values = (
        str(uuid.uuid4()),
        row.doc_index,
        row.markdown,
        row.image_path,
        datetime.now()

    )
    cursor.execute(query, values)
  except Exception as e:
    pass

In [194]:
conn.commit()

In [ ]:
def delete_high_index_documents():
    conn = None
    cursor = None
    try:
        # Connect to database
        conn = mysql.connector.connect(
            host='database-streamlit.czq8ik4asj60.ap-southeast-1.rds.amazonaws.com',
            user='admin',
            password='f*_anVhnyYFRK8veG',
            database='streamlit_ecliptor'
        )
        cursor = conn.cursor()

        # Execute delete query
        delete_query = "DELETE FROM documents WHERE doc_index > 198"
        cursor.execute(delete_query)

        # Commit the transaction
        conn.commit()

        print(f"Deleted {cursor.rowcount} rows")

    except Exception as e:
        print(f"Error: {e}")
        if conn:
            conn.rollback()
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()

# Execute the function
delete_high_index_documents()

Deleted 3095 rows